name: Get Wechat for Windows
on: 
  schedule:
  # 定时任务,cron表达式
    - cron: '0/120 * * * *'
  workflow_dispatch:
    
jobs:
  Get-Wechat-for-Windows:
    name: Get
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    #下载
    - name: get-file
      run: |
        echo $url
        curl -O https://dldir1v6.qq.com/weixin/Windows/WeChatSetup.exe
        chmod +x WeChatSetup.exe
    #重命名&提交
    - name: rename-push
      run: |
        TOKEN=${{ secrets.TOKEN }}
        current_time=$(date +"%Y%m%d%H%M%S")
        echo $current_time
        mkdir -p assets
        mv WeChatSetup.exe assets/WeChatSetup-${current_time}.exe

        git config --global user.email "$TOKEN@github.com"
        git config --global user.name "Yshengwang52005"
        git init
        git add .
        git commit -m "Auto Commit - $current_time"
        git remote add origin https://shengwang52005@github.com/shengwang52005/learn-actions.git
        git push -u origin main
